k8s-box:
    candy:
        base: fedora
    k8s-box-candy:
        candy:
            - '@github.com/opencharly/charly/candy/supervisord:v2026.183.1359'
            - '@github.com/opencharly/charly/candy/k8s-layer:v2026.183.1359'
